/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MyArticlesRouteImport } from './routes/my-articles'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticleCreateRouteImport } from './routes/article.create'
import { Route as ArticleIdRouteImport } from './routes/article.$id'
import { Route as ArticleIdIndexRouteImport } from './routes/article.$id.index'
import { Route as ArticleIdEditRouteImport } from './routes/article.$id.edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MyArticlesRoute = MyArticlesRouteImport.update({
  id: '/my-articles',
  path: '/my-articles',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleCreateRoute = ArticleCreateRouteImport.update({
  id: '/article/create',
  path: '/article/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleIdRoute = ArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleIdIndexRoute = ArticleIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticleIdRoute,
} as any)
const ArticleIdEditRoute = ArticleIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ArticleIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/my-articles': typeof MyArticlesRoute
  '/settings': typeof SettingsRoute
  '/article/$id': typeof ArticleIdRouteWithChildren
  '/article/create': typeof ArticleCreateRoute
  '/article/$id/edit': typeof ArticleIdEditRoute
  '/article/$id/': typeof ArticleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/my-articles': typeof MyArticlesRoute
  '/settings': typeof SettingsRoute
  '/article/create': typeof ArticleCreateRoute
  '/article/$id/edit': typeof ArticleIdEditRoute
  '/article/$id': typeof ArticleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/my-articles': typeof MyArticlesRoute
  '/settings': typeof SettingsRoute
  '/article/$id': typeof ArticleIdRouteWithChildren
  '/article/create': typeof ArticleCreateRoute
  '/article/$id/edit': typeof ArticleIdEditRoute
  '/article/$id/': typeof ArticleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/my-articles'
    | '/settings'
    | '/article/$id'
    | '/article/create'
    | '/article/$id/edit'
    | '/article/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/my-articles'
    | '/settings'
    | '/article/create'
    | '/article/$id/edit'
    | '/article/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/my-articles'
    | '/settings'
    | '/article/$id'
    | '/article/create'
    | '/article/$id/edit'
    | '/article/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  MyArticlesRoute: typeof MyArticlesRoute
  SettingsRoute: typeof SettingsRoute
  ArticleIdRoute: typeof ArticleIdRouteWithChildren
  ArticleCreateRoute: typeof ArticleCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-articles': {
      id: '/my-articles'
      path: '/my-articles'
      fullPath: '/my-articles'
      preLoaderRoute: typeof MyArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/create': {
      id: '/article/create'
      path: '/article/create'
      fullPath: '/article/create'
      preLoaderRoute: typeof ArticleCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$id': {
      id: '/article/$id'
      path: '/article/$id'
      fullPath: '/article/$id'
      preLoaderRoute: typeof ArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$id/': {
      id: '/article/$id/'
      path: '/'
      fullPath: '/article/$id/'
      preLoaderRoute: typeof ArticleIdIndexRouteImport
      parentRoute: typeof ArticleIdRoute
    }
    '/article/$id/edit': {
      id: '/article/$id/edit'
      path: '/edit'
      fullPath: '/article/$id/edit'
      preLoaderRoute: typeof ArticleIdEditRouteImport
      parentRoute: typeof ArticleIdRoute
    }
  }
}

interface ArticleIdRouteChildren {
  ArticleIdEditRoute: typeof ArticleIdEditRoute
  ArticleIdIndexRoute: typeof ArticleIdIndexRoute
}

const ArticleIdRouteChildren: ArticleIdRouteChildren = {
  ArticleIdEditRoute: ArticleIdEditRoute,
  ArticleIdIndexRoute: ArticleIdIndexRoute,
}

const ArticleIdRouteWithChildren = ArticleIdRoute._addFileChildren(
  ArticleIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  MyArticlesRoute: MyArticlesRoute,
  SettingsRoute: SettingsRoute,
  ArticleIdRoute: ArticleIdRouteWithChildren,
  ArticleCreateRoute: ArticleCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
