[build]
  command = "pnpm --filter client build"
  publish = "apps/client/dist/client"
  functions = "apps/client/.netlify/v1/functions"

[dev]
  command = "pnpm --filter client dev"
  targetPort = 3000
  port = 8888
